### ISSUE TITLE
Error en la página de inicio en la palabra días

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#10]
# Descripción
Error ortográfico en la palabra "dias" debajo de la descripción de Siempre Disponibles.

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/

# Resultado Esperado
Se espera que se muestre el texto: 
Siempre Disponibles
24 horas / 365 días

# Resultado Actual
La palabra "días" no tiene acento: 
Siempre Disponibles
24 horas / 365 **dias**

## Capturas de pantalla
![errordias](https://user-images.githubusercontent.com/39705612/40735454-d6fb2398-6400-11e8-8d67-77509aa03a52.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, documentado correctamente
