### ISSUE TITLE
Error en el texto del  mensaje que aparece al no estar logueado e intentar ingresar a un curso.

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#11]
# Descripción
Error ortográfico en la palabra "esta" del mensaje que aparece al intentar entrar a un curso sin estar logueado. 

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
Pre requisitos:
-No estar logueado con ninguna cuenta.
Pasos:
1. Navegar a la URL https://testerfabrik.com/
2. Dar click a cualquier link de INICIAR CURSO.

# Resultado Esperado
Se espera que se muestre el texto:
¡Ups!
Este contenido **está** reservado para nuestros suscriptores
Puedes adquirir tu membresía aquí o si ya eres socio solo accede a tu cuenta.

# Resultado Actual
La palabra "está" no tiene acento:
¡Ups!
Este contenido **esta** reservado para nuestros suscriptores
Puedes adquirir tu membresía aquí o si ya eres socio solo accede a tu cuenta.

## Capturas de pantalla
![errorerror](https://user-images.githubusercontent.com/39705612/40736205-fca99ca8-6402-11e8-8711-c979acf448cd.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, Documentación correcta
