### ISSUE TITLE
Error en link a Curso Tester Funcional Básico en la Página de Inicio

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#12]
# Descripción
Error ortográfico en la palabra "basico" en el link al Curso Tester Funcional Básico en la página de inicio.

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/

# Resultado Esperado
Se espera que se muestre el texto:
 Curso Tester Funcional **Básico** 

# Resultado Actual
La palabra Básico no tiene acento: Curso Tester Funcional **Basico** 

## Capturas de pantalla
![errorbasicobasico](https://user-images.githubusercontent.com/39705612/40736527-e1040992-6403-11e8-9089-a9d3c6e4446b.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, documentación correcta

**Comment by RubenMaldonado** [comment]
De momento quite el texto que estaba debajo de cada titulo. Para agregarlo vamos a necesitar una descripción de 25 palabras, pero creo que asi se ve bien.
