### ISSUE TITLE
Error en link a Curso de Selenium con Java Básico en la Página de Inicio 

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#13]
# Descripción
Error ortográfico en la palabra "basico" en el link al Curso de Selenium con Java Básico en la página de inicio.
## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/

# Resultado Esperado
Se espera que se muestre el texto:
Curso de Selenium con Java **Básico**

# Resultado Actual
La palabra "Básico" no tiene acento:
Curso de Selenium con Java **Basico**

## Capturas de pantalla
![errorbasicobasicobasico](https://user-images.githubusercontent.com/39705612/40738814-23c7f102-640a-11e8-94ae-b9df79ecb713.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, documentación correcta
