### ISSUE TITLE
Error en el link Diseño web por ruben maldonado

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#14]
# Descripción
El link Diseño web por ruben maldonado que se encuentra en el footer lleva a una página no disponible.

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/
2. Dar click en el link de Diseño web por ruben maldonado.

# Resultado Esperado
Se espera que el link nos lleve a la página deseada.

# Resultado Actual
El link nos lleva a una página no disponible.

## Capturas de pantalla
![errorrm](https://user-images.githubusercontent.com/39705612/40739249-4936d466-640b-11e8-96ad-f9121fcdc277.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
El link debe llevar a la página de @RubenMaldonado ,
