### ISSUE TITLE
Error en el título del capítulo 1 del Curso de Tester Funcional Básico ¿Por qué la Pruebas son Necesarias?

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#18]
# Descripción
En el título del capítulo 1 del Curso de Tester Funcional Básico, ¿Por qué la Pruebas son Necesarias?, el nombre del curso se encuentra mal escrito y tiene errores de ortografía. (Curso de Testing Funcional Básico 1 ¿Porqué la Pruebas son Necesarias?)

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/
2. Ingresar al Curso Tester Funcional Básico.
3. Ir al link Curso de Tester Funcional Básico 1 ¿Por qué la Pruebas son Necesarias?

# Resultado Esperado
Se espera que el título del capítulo este escrito como:
Curso de Tester Funcional Básico 1. 
¿Por qué la Pruebas son Necesarias?

# Resultado Actual
Actualmente la palabra Tester dice otra cosa y la palabra ¿Por qué? está escrita junta:
Curso de Testing Funcional Básico 1. 
¿Porqué la Pruebas son Necesarias?

## Capturas de pantalla
![errortestingporque](https://user-images.githubusercontent.com/39705612/40789469-19bc1324-64b8-11e8-9f6f-2548eece2414.png)
![errorporque](https://user-images.githubusercontent.com/39705612/40789475-1de56cde-64b8-11e8-9060-bde8ba4151bc.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, documentación correcta
