### ISSUE TITLE
Error en el título del capítulo 2 del curso Tester Funcional Básico ¿Qué son las Pruebas?

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#19]
# Descripción
Error ortográfico en la palabra "basico" del título del capítulo 2 del curso Tester Funcional Básico ¿Qué son las Pruebas?.

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/
2. Ingresar al Curso Tester Funcional Básico.
3. Ir al link Curso de Tester Funcional Básico 2 ¿Qué son las Pruebas?

# Resultado Esperado
El título del capítulo debe aparecer como:
Curso de Tester Funcional Básico 2. ¿Qué son las Pruebas?

# Resultado Actual
Actualmente la palabra "Básico" no esta acentuada:
Curso de Tester Funcional Basico 2. ¿Qué son las Pruebas?

## Capturas de pantalla
![errorbasico2](https://user-images.githubusercontent.com/39705612/40856114-4c61d658-659c-11e8-8d1a-59a4e311961e.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, documentación correcta

**Comment by RubenMaldonado** [comment]
Done!
