### ISSUE TITLE
Error en el link ¿Quiénes somos?

### ISSUE THREAD

**Issue by gsanchezm** [gsanchezm/Features_Testing_TesterFabrik#2]
# Descripción
Error ortográfico en la palabra 'Quienes'

## Sistema Operativo
- [x] Windows 10
- [x] MAC
- [x] Linux
- [x] Ubuntu

## Navegador
- [x] Chrome
- [x] Firefox
- [x] Explorer
- [x] Edge
- [x] Safari 

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/

# Resultado Esperado
Se espera que se muestre el texto: 
¿Quiénes Somos?

# Resultado Actual
La palabra Quiénes, no tiene acento: ¿**Quienes** Somos?

## Capturas de pantalla
![image](https://user-images.githubusercontent.com/24705055/40623239-6de4c6f2-626b-11e8-9d91-008eb246a857.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, documentado correctamente

**Comment by RubenMaldonado** [comment]
Fixed!

**Comment by RubenMaldonado** [comment]
Fixed!
