### ISSUE TITLE
Error en los enlaces a los otros capítulos del capítulo 2 del Curso de Tester Funcional Básico

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#20]
# Descripción
En el capítulo 2 del Curso de Tester Funcional Básico el título del la sección de enlaces a otros capítulos tiene errores de ortografía además de otro formato distinto a como se ve en los demás capítulos.
 
## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/
2. Ingresar al Curso Tester Funcional Básico.
3. Ir al link Curso de Tester Funcional Básico 2 ¿Qué son las Pruebas?.

# Resultado Esperado
Se espera que el título de la sección de enlaces a otros capítulos sea igual de los demás capítulos.

# Resultado Actual
El título de la sección de enlaces a otros capítulos es mas larga que en los demás capítulos y la palabra "Básico" tiene errores ortográficos:
Todas las lecciones del curso**: Tester Funcional Basico**
 
## Capturas de pantalla
![errortodas](https://user-images.githubusercontent.com/39705612/40856586-004b4d1a-659e-11e8-99dd-aae4548afcbb.png)
![goodtodas](https://user-images.githubusercontent.com/39705612/40856589-041d4fba-659e-11e8-9b6a-450d26fa28a0.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, documentación correcta

**Comment by RubenMaldonado** [comment]
Fixed
