### ISSUE TITLE
Error en la introducción del capitulo 9 del Curso de Tester Funcional Básico

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#21]
# Descripción
En el texto de Introducción del Curso de Tester Funcional Básico tiene un apóstrofe antes de la palabra pruebas que no debe ir ahí. 

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/
2. Ingresar al Curso Tester Funcional Básico.
3. Ir al link Curso de Tester Funcional Básico 9. Pruebas de Mantenimiento.

# Resultado Esperado
Introducción
Una vez desplegado, un sistema a menudo está en servicio durante años o incluso décadas. Durante este tiempo, el sistema y su entorno operativo a menudo se corrige, cambia o amplía. Las pruebas que se ejecutan durante esta fase del ciclo de vida se llaman pruebas de mantenimiento. Tenga en cuenta que las pruebas de mantenimiento son diferentes de las pruebas de mantenimiento, que define qué tan fácil es mantener el sistema. El proceso de desarrollo y prueba aplicable a los nuevos desarrollos no cambia fundamentalmente con fines de mantenimiento.

# Resultado Actual
Introducción
Una vez desplegado, un sistema a menudo está en servicio durante años o incluso décadas. Durante este tiempo, el sistema y su entorno operativo a menudo se corrige, cambia o amplía. Las pruebas que se ejecutan durante esta fase del ciclo de vida se llaman **‘**pruebas de mantenimiento. Tenga en cuenta que las pruebas de mantenimiento son diferentes de las pruebas de mantenimiento, que define qué tan fácil es mantener el sistema. El proceso de desarrollo y prueba aplicable a los nuevos desarrollos no cambia fundamentalmente con fines de mantenimiento.

## Capturas de pantalla
![errorapos](https://user-images.githubusercontent.com/39705612/40857090-af32fa34-659f-11e8-82ea-21ae1bb41613.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, documentación del bug correcta

**Comment by RubenMaldonado** [comment]
Fixed!
