### ISSUE TITLE
Error en los links de ¿Quiénes somos?

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#23]
# Descripción
Los links a facebook, twitter y google+ que se encuentran en la página ¿Quiénes somos? te redireccionan a la misma página de ¿Quiénes somos?

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/
2. Ir a la página de "¿Quiénes somos?".
3. Dar click a los links de facebook, twitter o google+. 

# Resultado Esperado
Se espera que al dar click el usuario sea redireccionado a la página que se indica.

# Resultado Actual
Al dar click a cualquiera de los links el usuario es redireccionado a la página de ¿Quiénes somos?.

## Capturas de pantalla
N/A

## Notas
N/A

**Comment by RubenMaldonado** [comment]
De momento quite los links, necesitamos definir si agreamos algo o no, eran parte del diseno.
