### ISSUE TITLE
Dos personas pueden iniciar sesión con las mismas credenciales al mismo tiempo.

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#24]
# Descripción
Dos personas pueden iniciar sesión con las mismas credenciales al mismo tiempo.

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/
2. Iniciar sesión.
3. Iniciar sesión desde un dispositivo o  navegador diferente.

# Resultado Esperado
El usuario no debe poder ingresar a su cuenta si ya está loggeado en otro dispositivo. 

# Resultado Actual
Varias personas con las mismas credenciales pueden estar loggeadas al mismo tiempo. 

## Capturas de pantalla
N/A

## Notas
N/A

**Comment by RubenMaldonado** [comment]
Listo, se puede probar iniciando sesion en dos navegadores diferentes y/o usando modo incognito, sera cerrada la sesion al dar click en otro enlace.
