### ISSUE TITLE
Error en página de inicio "más fácil"

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#3]
# Descripción
Error ortográfico en las palabras "mas" y "facil" ya que estas llevan acento.

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/

# Resultado Esperado
Se espera que se muestre el texto:
Los cursos de testing online de TesterFabrik.com son la forma más fácil, practica e interesante que tienes para lograr convertirte en un profesional del testing de software.

# Resultado Actual
Las palabras más y fácil no tienen acentos:
Los cursos de testing online de TesterFabrik.com son la forma **mas facil**, practica e interesante que tienes para lograr convertirte en un profesional del testing de software.

## Capturas de pantalla
![errormasfacil](https://user-images.githubusercontent.com/39705612/40677415-337e4aaa-6343-11e8-8702-b00c6f3fdaaf.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, documentado correctamente
