### ISSUE TITLE
Error en la conclusión del capítulo # 03. Introducción a Selenium WebDriver del Curso de Selenium con Java Básico

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#39]
# Descripción
Error ortográfico en el texto conclusión del capítulo # 03. Introducción a Selenium WebDriver del Curso de Selenium con Java Básico en las palabras "Conclusión" y "Están".

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/.
2. Ingresar al Curso de Selenium con Java Básico.
3. Ir al link Curso de Selenium con Java Básico # 03. Introducción a Selenium WebDriver.

# Resultado Esperado
Se espera que se muestre el siguiente texto:
**Conclusión**

Al hablar de WebDriver, estamos hablando de una herramienta potente para la creación de pruebas automatizadas, podemos implementarla con varios lenguajes de programación como lo son Java, C#, Python, entre otros; la arquitectura general se compone de cuatro escenarios que **están** interactuando entre sí (WebDriver API, WebDriver SPI, JSON Wire Protocol y Selenium Server) para manejar de forma eficiente nuestra ejecución sobre navegadores.

# Resultado Actual
Las palabras "Conclusión" y "están" no están acentuadas:
**Conclusion**
Al hablar de WebDriver, estamos hablando de una herramienta potente para la creación de pruebas automatizadas, podemos implementarla con varios lenguajes de programación como lo es Java, C#, Python, entre otros; la arquitectura general se compone de cuatro escenarios que **estan** interactuando entre si (WebDriver API, WebDriver SPI, JSON Wire Protocol y Selenium Server) para manejar de forma eficiente nuestra ejecución sobre navegadores.

## Capturas de pantalla
![conlusion03introduccion a selenium webdriver](https://user-images.githubusercontent.com/39705612/41305217-db129254-6e37-11e8-9eec-8c58e8de9ca4.png)

## Notas
N/A

**Comment by RubenMaldonado** [comment]
Done
