### ISSUE TITLE
Error en botón SUSCRIBIRSE

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#4]
# Descripción
Error ortográfico en la palabra "dolares" ya que le falta el acento.

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/

# Resultado Esperado
Se espera que se muestre el texto: SUSCRIBIRSE ($12 DÓLARES / MES)

# Resultado Actual
La palabra dólares, no tiene acento: SUSCRIBIRSE ($12 **DOLARES** / MES)

## Capturas de pantalla
![errordolares](https://user-images.githubusercontent.com/39705612/40677822-70fe8e48-6344-11e8-9d19-45496749b250.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, documentado correctamente
