### ISSUE TITLE
Error los links a los videos del capítulo # 04. Instalación de herramientas del Curso de Selenium con Java Básico

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#41]
# Descripción
Los links a los videos en el capítulo 4. Instalación de Herramientas del Curso de Selenium con Java Básico son incorrectos.

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/.
2. Ingresar al Curso de Selenium con Java Básico.
3. Ir al link Curso de Selenium con Java Básico # 04. Instalación de herramientas.

# Resultado Esperado
Se espera que el video que se muestre corresponda con el título que se muestra encima de el.
*Instalación Chocolatey:* https://vimeo.com/240397875
*Instalación JDK:* https://vimeo.com/240399735
*Instalación IntelliJ:* https://vimeo.com/240402804
*Descarga Selenium Jars y Chromedriver:* https://vimeo.com/240405294

# Resultado Actual
Los enlaces se encuentran de la siguiente manera:
*Instalación Chocolatey:* https://vimeo.com/240397875
*Instalación JDK:* https://vimeo.com/240402804
*Instalación IntelliJ:* https://vimeo.com/240405294
*Descarga Selenium Jars y Chromedriver:* https://vimeo.com/240405294

## Capturas de pantalla
N/A

## Notas
N/A

**Comment by RubenMaldonado** [comment]
@marianaqv  @gsanchezm el URL del JDK es incorrecto, los demas ya quedaron resueltos.
