### ISSUE TITLE
Error en la conclusión del capítulo # 04. Instalación de herramientas del Curso de Selenium con Java Básico

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#42]
# Descripción
Errores ortográficos en el texto de conclusión del capítulo 4 del Curso de Selenium con Java Básico en las palabras "conclusión","nuestra","siglas" y "sus".

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/.
2. Ingresar al Curso de Selenium con Java Básico.
3. Ir al link Curso de Selenium con Java Básico # 04. Instalación de herramientas.

# Resultado Esperado
Se espera que se muestre el siguiente texto:
Conclusión
Para este curso es necesario tener en nuestra máquina JDK así como un Entorno de Desarrollo Integrado (IDE por sus siglas en inglés), e IntelliJ es la opción adecuada a nuestras necesidades, además con la ayuda de Chocolatey podemos descargar software de manera sencilla y rápida. Por último pero no menos importante, vimos de donde descargar los Jars de Selenium para poder crear nuestros scripts automatizados, así como nuestro driver que se encargará de manipular nuestro navegador Chrome.

# Resultado Actual
Actualmente algunas palabras están mal escritas:
**Conclusion**
Para este curso es necesario tener en **nustra** máquina JDK así como un Entorno de Desarrollo Integrado (IDE por **sis suglas** en inglés), e IntelliJ es la opción adecuada a nuestras necesidades, además con la ayuda de Chocolatey podemos descargar software de manera sencilla y rápida. Por último pero no menos importante, vimos de donde descargar los Jars de Selenium para poder crear nuestros scripts automatizados, así como nuestro driver que se encargará de manipular nuestro navegador Chrome.

## Capturas de pantalla
![error42](https://user-images.githubusercontent.com/39705612/41359432-1bfb20a2-6ef0-11e8-9f15-c1bf90fbc364.png)

## Notas
N/A

**Comment by RubenMaldonado** [comment]
Done!
