### ISSUE TITLE
Error en descripción de formulario Soporte Premium

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#5]
# Descripción
Error ortográfico en la descripción del formulario de Soporte Premium en las palabras "A traves" y "podras" ya que estas llevan acento.

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/.
2. Dar click a Soporte Premium.

# Resultado Esperado
Se espera que se muestre el texto:
A través de este formulario podrás contactar a todos nuestros instructores con preguntas o dudas sobre cualquiera de nuestros cursos.

# Resultado Actual
Las palabras "A través" y "podrás" no tienen acentos:
A **traves** de este formulario **podras** contactar a todos nuestros instructores con preguntas o dudas sobre cualquiera de nuestros cursos.

## Capturas de pantalla
![erroratravespodras](https://user-images.githubusercontent.com/39705612/40732922-1921b798-63fa-11e8-8368-da0f552ac917.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, documentado correctamente
