### ISSUE TITLE
Error en texto debajo del Formulario de Soporte

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#6]
# Descripción
Error ortográfico en las palabras "mas" y "antiguedad" del texto que se encuentra debajo del formulario de Soporte Premium.

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/.
2. Dar click a Soporte Premium.

# Resultado Esperado
Se espera que se muestre el texto:
Al ser suscriptor premium, puedes sugerirnos que cursos nuevos quieres que agreguemos ya que tus sugerencias se valoran más de acuerdo a tu antigüedad.

# Resultado Actual
La palabra "más" debe llevar acento y la palabra "antigüedad" debe llevar diéresis:
Al ser suscriptor premium, puedes sugerirnos que cursos nuevos quieres que agreguemos ya que tus sugerencias se valoran **mas** de acuerdo a tu **antiguedad**.

## Capturas de pantalla
![errormasantiguedad](https://user-images.githubusercontent.com/39705612/40733653-cc4a4528-63fb-11e8-93e1-d5d6d5771cfa.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, documentado correctamente
