### ISSUE TITLE
Error en el texto ¿Quiénes Somos? 

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#7]
# Descripción
Error ortográfico en la palabra 'Quienes'

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/
2. Dar click en el link ¿Quiénes Somos?.

# Resultado Esperado
Se espera que se muestre el texto:
¿Quiénes Somos?

# Resultado Actual
La palabra Quiénes, no tiene acento: ¿Quienes Somos?

## Capturas de pantalla
![errorquienes](https://user-images.githubusercontent.com/39705612/40734023-dae83bac-63fc-11e8-92ed-34f722747aaa.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, Documentado correctamente
