### ISSUE TITLE
Error en el texto del segundo punto de Tres cosas sobre nosotros

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#8]
# Descripción
Error ortográfico en la palabra "educacion" en el segundo punto de Tres cosas sobre nosotros y falta la palabra "de".

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/
2. Dar click en el link ¿Quiénes Somos?.

# Resultado Esperado
Se espera que se muestre el texto:
Creemos firmemente en que la educación profesional debe de ser sencilla, clara y directa sin rodeos ni temas **de** relleno.

# Resultado Actual

La palabra "educación" no tiene acento y falta la palabra de:
Creemos firmemente en que la **educacion** profesional debe de ser sencilla, clara y directa sin rodeos ni temas "" relleno.

## Capturas de pantalla
![erroreducacion](https://user-images.githubusercontent.com/39705612/40734319-ad91d3e2-63fd-11e8-8127-0d3e728ffa0a.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, documentado correctamente
