### ISSUE TITLE
 Error en el texto del tercer punto de Tres cosas sobre nosotros

### ISSUE THREAD

**Issue by gilbertoSM** [gsanchezm/Features_Testing_TesterFabrik#9]
# Descripción
Error ortográfico en la palabra "promocion" en el tercer punto de Tres cosas sobre nosotros. 

## Sistema Operativo
- [ ] Windows
- [ ] MAC
- [ ] Linux
- [ ] Ubuntu
- [x] Todos

## Navegador
- [ ] Chrome
- [ ] Firefox
- [ ] Explorer
- [ ] Edge
- [ ] Safari 
- [x] Todos

# Pasos para Reproducir
1. Navegar a la URL https://testerfabrik.com/
2. Dar click en el link ¿Quiénes Somos?.

# Resultado Esperado
Se espera que se muestre el texto:
Confiamos en que nuestros cursos te ayudaran a conseguir el trabajo o la promoción que tanto te mereces al mejor precio en el mercado.

# Resultado Actual
La palabra "promoción" no tiene acento:
Confiamos en que nuestros cursos te ayudaran a conseguir el trabajo o la **promocion** que tanto te mereces al mejor precio en el mercado

## Capturas de pantalla
![errorpromocion](https://user-images.githubusercontent.com/39705612/40735126-fbcfd39a-63ff-11e8-82e5-8ee30db9e624.png)

## Notas
N/A

**Comment by gsanchezm** [comment]
Revisado, documentado correctamente
